[sonic-config-engine]: Improve comparison between default and supported breakout modes.
oleksandrivantsiv/sonic-buildimage pull request #1
Opened 2021-11-09 13:53 UTC by oleksandrivantsiv

resolves #7958

#### Why I did it

The previous implementation of sonic-cfggen did a simple comparison between default breakout mode in
hwsku.json and supported modes in platform.json. To set a different default speed in hwsku.json
it was required to add one more entry to supported modes in platfrom.json file:

1x10G[100G,50G] vs 1x100G[50G,10G]

The new implementation does more intelligent parsing and analysis of supported and default modes. It
allows changing default speed without adding a new entry to platform.json.

#### How I did it

Add more intelligent parsing and analysis of supported and default modes.

#### How to verify it

Run regression

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106

#### Description for the changelog

#### A picture of a cute animal (not mandatory but encouraged)

2021-11-10 03:45 UTC, alexrallen requested changes
Thanks for this enhancement!

In your PR message I would prefer there be a bit more detail in the "How to Validate" section than "Run Regression"

Just briefly describe what manual testing you did and if there are any unit tests present, this will allow the reviewer to quickly understand what has already been validated prior to the review.

2021-11-10 11:43 UTC, oleksandrivantsiv commented on src/sonic-config-engine/portconfig.py
> +            return "{} {} [{}] {}".format(self.port_num, self.default_speed, ", ".join(
I left this method only for debugging purposes. Removing it since it is not used in the code.

2021-11-10 11:44 UTC, oleksandrivantsiv commented on src/sonic-config-engine/portconfig.py
> +        if re.search("\+",bmode) is not None:
Agree

2021-11-10 11:45 UTC, oleksandrivantsiv commented on src/sonic-config-engine/portconfig.py
> +        for entrie in self._breakout_mode_entry:
typo, changed

2021-11-10 11:46 UTC, oleksandrivantsiv commented on src/sonic-config-engine/portconfig.py
> +                if not entrie.default_speed.endswith('G'):
It is not part of dynamic port breakout HDL. I suggest leaving it as is

2021-11-10 11:47 UTC, oleksandrivantsiv commented on src/sonic-config-engine/portconfig.py
> +        def __init__(self, port_num, default_speed, supported_speed, assigned_lanes_num=None):
Agree

2021-11-10 11:50 UTC, oleksandrivantsiv commented on src/sonic-config-engine/portconfig.py
> +            return int(assigned_lanes_num[1:-1])
I don't think that this is needed. The exception that "int" raises indicates the problem.

2021-11-10 13:28 UTC, oleksandrivantsiv commented
@alexrallen Please review

2021-11-14 06:14 UTC, dgsudharsan requested changes

2021-11-14 06:14 UTC, dgsudharsan commented on src/sonic-config-engine/tests/sample_output/platform_output.json
> -  "Ethernet8": {
Why are we having such a huge diff in this file? Shouldn't it be only for the entries you added?

2021-11-14 06:14 UTC, dgsudharsan commented on src/sonic-config-engine/portconfig.py
> +                if not entrie.default_speed.endswith('G'):
Please add the logic back as discussed offline.

2021-11-15 10:59 UTC, oleksandrivantsiv commented on src/sonic-config-engine/portconfig.py
> +            self.supported_speed = set((default_speed, ))
To be able to compare breakout mode supported speeds I'm using "set" collection. As the input parameter set expects to have an iterable value. "default_speed" has string type. The string is iterable. If we pass "default_speed" as a parameter to set each character will be used as separated entry in the set:
```
In [2]: set("10G")
Out[2]: {'0', '1', 'G'}
```
To prevent this I'm passing a tuple with one element as an input parameter:
```
In [3]: set(("10G", ))
Out[3]: {'10G'}
```

2021-11-15 12:32 UTC, oleksandrivantsiv commented on src/sonic-config-engine/portconfig.py
> +                if not entrie.default_speed.endswith('G'):
done

2021-11-15 12:32 UTC, oleksandrivantsiv commented on src/sonic-config-engine/portconfig.py
> +    def __init__(self, name, bmode, capabilities):
done

2021-11-15 12:37 UTC, oleksandrivantsiv commented on src/sonic-config-engine/tests/sample_output/platform_output.json
> -  "Ethernet8": {
This file has autogenerated output from sonic-cfggen utility. It was easier for me to run sonic-cfggen utility again and save the output to the file rather than edit it manually. However, it makes diff unreadable so in the last commit, I added new entries manually.

2021-11-15 18:26 UTC, alexrallen approved these changes
All changes look good, thanks.

2021-11-15 20:38 UTC, dgsudharsan approved these changes

2021-11-16 20:22 UTC, merged